### ISSUE TITLE
error console.log(res[0]);  // '110.522000' - market bid

### ISSUE THREAD

**Issue by AHGsystems** [BonneVoyager/node-mt4-zmq-bridge#1]
HI! i try a get price from this example:

// price.js

const mt4zmqBridge = require('mt4-zmq-bridge');
const zmqBridge = mt4zmqBridge.connect('tcp://127.0.0.1:5555', 'tcp://127.0.0.1:5556');
zmqBridge.request(mt4zmqBridge.REQUEST_RATES, "USDJPY", (err, res) => {
  console.log(res);     // [ '110.522000', '110.542000', 'USDJPY' ]
  console.log(res[0]);  // '110.522000' - market bid
  console.log(res[1]);  // '110.542000' - market ask
});

// ....................................................................................................
npm test works fine, but when i try run " node price.js" i get this error

undefined
/home/node-mt4-zmq-bridge/jborrar_0.js:5
  console.log(res[0]);  // '110.522000' - market bid
..............................................................................................................

I try to make a loop to get the price every minute

**Comment by BonneVoyager** [comment]
Hi @AHGsystems,

You were probably not connected to MetaTrader4 before sending the request.

There should be an error in `err`. What does it say?

**Comment by CharlesM1** [comment]
Hi,
I have the same problem, when I run file.js, only "undefined" is returned. 
In the mt4 terminal it appears "initialized" in the expert advisors section.

**Comment by CharlesM1** [comment]
Hi.
I tried and it returned "The ZMQ REQ connection is closed.". So I changed reqConnected and pullConnected in mt4_bridge / index.js to true and the rates appear.

**Comment by donggiggedin** [comment]
I'm having the same problem

**Comment by BonneVoyager** [comment]
The general problem is that a request shouldn't be sent before the connection is established. It could be queued instead.

I'm working on releasing a new minor version which should fix this issue, but I'm testing it at the moment.

**Comment by donggiggedin** [comment]
thanks @BonneVoyager for your support. Hope that it will not take long. Looking forward to it.

**Comment by BonneVoyager** [comment]
Closing this and continuing on https://github.com/BonneVoyager/node-mt4-zmq-bridge/issues/3
