### ISSUE TITLE
support for MT5/MQL5

### ISSUE THREAD

**Issue by baopn** [BonneVoyager/node-mt4-zmq-bridge#2]
Hi BonneVoyager,

Sorry for creating this issue, but I can't find your contact to consult you about supporting for MT5/MQL5, something like **node-mt5-zmq-bridge**.

I downloaded the current MT4 version on https://www.metatrader4.com/en/download and the **MetaTrader4Bridge.mq4** on https://github.com/BonneVoyager/MetaTrader4-Bridge, but they don't seem to compatible. The downloaded MT4 don't support MQL4 so the EA file was not imported to the Expert advisers correctly (although I complied it successfully in MetaEditor).

Do you have any plan for supporting the package on MT5/MQL5? Or could you share me your idea on this?

Thanks.

**Comment by BonneVoyager** [comment]
Hi @baopn,

Thanks for contacting me.

Currently I'm not planning to support MT5, as a majority of brokers still support MT4. Also, MT5 EA would require a fresh implementation, because there are many differences in both languages when comparing MQL4 and 5.

Regards

**Comment by baopn** [comment]
Hi @BonneVoyager,

Thanks for sharing your plan.
So the package only works with separate MT4 apps of brokers (FXTM, FXCM,...), is it right?.  I cannot find a general MT4 app that supports multi-brokers because the official MT4 app ( https://www.metatrader4.com/en/download) does not support MQL4 anymore.

Maybe, I will find an another solution.

Thanks

**Comment by BonneVoyager** [comment]
Hi @baopn,

Yes, it works with broker-specific MT4 clients.
I didn't try the package with official MT4 client. Although that shouldn't be much of a difference to the package when it comes to support of MQL4 as long as it is MT4 client.

Good luck with searching.

**Comment by baopn** [comment]
Thank you for the information.

**Comment by Edorenta** [comment]
> Hi @baopn,
> 
> Yes, it works with broker-specific MT4 clients.
> I didn't try the package with official MT4 client. Although that shouldn't be much of a difference to the package when it comes to support of MQL4 as long as it is MT4 client.
> 
> Good luck with searching.

Hi Krzysztof,
I like the simplicity of your implementations.
Are you using the zmq bridge yourself, or did you do this out of curiosity / for a client?
Cheers

**Comment by BonneVoyager** [comment]
Hi @Edorenta,

Thank you for your kind words.
I'm using this ZMQ bridge for my personal project and it works flawlessly for almost two years already.

Cheers

**Comment by Umair-A** [comment]
Hi @BonneVoyager 
I'm using your mt4-zmq-bridge for connecting to mt4 accounts.
Is there any way we are able to connect with mt5 account.

**Comment by BonneVoyager** [comment]
> Hi @BonneVoyager
> I'm using your mt4-zmq-bridge for connecting to mt4 accounts.
> Is there any way we are able to connect with mt5 account.

Hi @Umair-A, that would require another library. This lib doesn't support MT5.

**Comment by Umair-A** [comment]
Thanks, @BonneVoyager  for your kind response. Please suggest to me some other libraries if you can.

**Comment by BonneVoyager** [comment]
> Thanks, @BonneVoyager for your kind response. Please suggest to me some other libraries if you can.

No problem @Umair-A. I wasn't using MT5 for a while, so I'm not sure what's our there right now.

**Comment by Umair-A** [comment]
Thanks
