### ISSUE TITLE
Timeout exception when error

### ISSUE THREAD

**Issue by donggiggedin** [BonneVoyager/node-mt4-zmq-bridge#3]
Hi @BonneVoyager ,
Thanks so much for your contribution to the society. 
I'm using your library and love it. But I'm having a few problems.
This is my code

`console.log(${mt4zmqBridge.REQUEST_TRADE_OPEN}|${symbol}|${orderType}|${volume}|${open_price}|0|${sl}|${tp}||0|${mt4zmqBridge.UNIT_CONTRACTS});
					const response = await zmqBridge.request(mt4zmqBridge.REQUEST_TRADE_OPEN, symbol, orderType, volume, open_price, 0, sl, tp, "", 0, mt4zmqBridge.UNIT_CONTRACTS);
`

I tried to send a buy limit request, console.log prints : 
`11|USDCHF|2|0.2|0.921690|0|0.921610|0.922090||0|0`

Then the mt4 logs return error : 
`1|1|130`

No errors is caught by the catch block. 
But after a few seconds it caught : 
`0|forex  | Error Error: ZMQ Request timeout.
0|forex  |     at requestTimeoutCallback (/var/www/html/forex/api/node_modules/mt4-zmq-bridge/index.js:169:8)
0|forex  |     at listOnTimeout (internal/timers.js:549:17)
0|forex  |     at processTimers (internal/timers.js:492:7)`

I don't know why I can not send the buy limit request. I tried a lot of time. I just code to copy the request of my another account.

**Comment by BonneVoyager** [comment]
Hi @donggiggedin, I appreciate your feedback!
I just published `v1.2.0`. Could you try that version and see if it fixed your`Error: ZMQ Request timeout` error?
