### ISSUE TITLE
Can this be used for reading alerts from dashboard indicator

### ISSUE THREAD

**Issue by eringiso** [BonneVoyager/node-mt4-zmq-bridge#4]
I have a custom dashboard type indicator that scans around 10 pairs with multi time frame and alerts via a pop up and 
push notification, I want to catch those alerts and use them for auto trading or sending them as signals can you please give an example for reading the alerts

**Comment by BonneVoyager** [comment]
@eringiso as far as I know it's possible to read MT4 alerts from the logs, but currently this library doesn't support that.

**Comment by eringiso** [comment]
hi @BonneVoyager i've tried to parse the log files using this npm package https://github.com/adam-p/text-file-follower
but i'm not receiving the file changes instantly with the mt4 log file it only recoginses when i view the alerts in the expert tab in mt4 otherwise it's not detecting any changes(see the attached picture)
<img width="1251" alt="git" src="https://user-images.githubusercontent.com/63807310/98681288-8e02ba80-2388-11eb-9b84-46aa0d646bf9.png">
so i tried to parse a normal text  file and it works instantly, i think the issue is with mt4 log file only,
could you please take a look at the attached indicator file i'm trying to parse it's alerts and tell me what needs to be done to get 
the file changes instantly i'm using windows 10

[PAD.zip](https://github.com/BonneVoyager/node-mt4-zmq-bridge/files/5517710/PAD.zip)
