### ISSUE TITLE
Error in Order Creation is showing the lines of codes where it failed.

### ISSUE THREAD

**Issue by cybermizrach** [BonneVoyager/node-mt4-zmq-bridge#9]
I tried creating a Sell Limit Order which entry price is below the current market price but I got the following error.  I think it should only display the error message "Error: Invalid stops." but not the lines of codes where it failed.

```
Error: Invalid stops.
    at requestCallback (\MT4V2\node_modules\mt4-zmq-bridge\index.js:150:20)
    at Object.onceWrapper (events.js:482:26)
    at EventEmitter.emit (events.js:375:28)
    at exports.Socket.<anonymous> (\MT4V2\node_modules\mt4-zmq-bridge\index.js:267:19)
    at exports.Socket.emit (events.js:375:28)
    at exports.Socket.Socket._emitMessage (\MT4V2\node_modules\zeromq\lib\index.js:647:10)
    at exports.Socket.Socket._flushRead (\MT4V2\node_modules\zeromq\lib\index.js:660:10)
    at exports.Socket.Socket._flushReads (\MT4V2\node_modules\zeromq\lib\index.js:696:15)
    at Immediate.<anonymous> (\MT4V2\node_modules\zeromq\lib\index.js:307:12)
```

**Comment by BonneVoyager** [comment]
@cybermizrach what code did you use? There is an example in README file on how to open a limit order:
```js
zmqBridge.request(
  mt4zmqBridge.REQUEST_TRADE_OPEN,  // request type
  'USDJPY',                         // market symbol
  mt4zmqBridge.OP_BUYLIMIT,         // order type
  1.2,                              // volume
  105.23,                           // price
  0,                                // slippage
  100.10,                           // stop loss
  110.76,                           // take profit
  'evening trade',                  // comment
  0,                                // magic number
  mt4zmqBridge.UNIT_CONTRACTS       // unit type
, (err, res) => {
  console.log(res); // [ '140734412' ]
});
```

**Comment by cybermizrach** [comment]
@BonneVoyager  Thank you for your response. I used the code above.  The code works fine without any issues if I use the code below to place a buy limit in which the **order price is below or equal to the current price**.

Since I'm testing different scenarios, I've tested the negative scenarios. No issues with displaying the error message "**Error: Invalid stops.**"  when I place a buy limit in which the order price is below the current market price. But the extra error stack below should not be displayed:

```
    at requestCallback (\MT4V2\node_modules\mt4-zmq-bridge\index.js:150:20)
    at Object.onceWrapper (events.js:482:26)
    at EventEmitter.emit (events.js:375:28)
    at exports.Socket.<anonymous> (\MT4V2\node_modules\mt4-zmq-bridge\index.js:267:19)
    at exports.Socket.emit (events.js:375:28)
    at exports.Socket.Socket._emitMessage (\MT4V2\node_modules\zeromq\lib\index.js:647:10)
    at exports.Socket.Socket._flushRead (\MT4V2\node_modules\zeromq\lib\index.js:660:10)
    at exports.Socket.Socket._flushReads (\MT4V2\node_modules\zeromq\lib\index.js:696:15)
    at Immediate.<anonymous> (\MT4V2\node_modules\zeromq\lib\index.js:307:12)
```

**Negative Scenario**
Place a buy limit in which the order price is below the current market price

Current Market Price: 110.601
Order Entry Price: 120.597
Order Stop Loss:  119.10
Order Take Profit: 130.76

```
      console.log("createOrder1")
      zmqBridge.request(
        mt4zmqBridge.REQUEST_TRADE_OPEN,  // request type
        'USDJPY',                         // market symbol
        mt4zmqBridge.OP_BUYLIMIT,         // order type
        0.01,                              // volume
        120.597,                           // price
        0,                                // slippage
        119.10,                           // stop loss
        130.76,                           // take profit
        'evening trade',                  // comment
        0,                                // magic number
        mt4zmqBridge.UNIT_CONTRACTS       // unit type
      , (err, res) => {
        console.log(err); 
        console.log(res); // [ '140734412' ]
      });
```

Please let me know if it make sense.

**Comment by BonneVoyager** [comment]
@cybermizrach I can see what the problem is now, thank you for finding it out. I must have not considered such a scenario before. The implementation probably should allow creating a limit order in which the order price is above/below (buy/sell) the current price.

I shall check this in detail and fix the potential issue, but not earlier than in August. Thank you for your patience.

**Comment by cybermizrach** [comment]
@BonneVoyager - Thank you for the response. I've updated the description of the scenario above. The order information is still correct
It should be "Place a buy limit in which the order price is **ABOVE** the current market price."
Instead of "Place a buy limit in which the order price is **BELOW** the current market price."

The MT4 Error message is correct to reject the order above but misleading.  I think a user-friendly error message should be displayed instead.
For Buy Limit, the price must be **ABOVE** the market price.
For Sell Limit,  the price must be **BELOW** the market price. 

You can also check in MT4 which types of orders are allowed below or above the market price.

Thanks again for your help!

**Comment by BonneVoyager** [comment]
Hi @cybermizrach! I looked into this again, and I'm not sure how to address this. `Error: Invalid stops.` is indeed an error coming from MetaTrader 4, so I think any special handling of this error should happen on the implementation side of an application using this package.

One way to achieve that would be code such as this:

```js
, (err, res) => {
  if (err) {
    if (err.message.includes('Invalid stops')) {
      doSomethingAboutInvalidStops()
    } else {
      doSomethingAboutAnError()
    }
  } else {
    doSomethingElse()
  }
})
```

What do you think about that? Or did you have something else in mind?
